export const DAYCARE_LIST_REQUEST = 'DAYCARE_LIST_REQUEST'
export const DAYCARE_LIST_SUCCESS = 'DAYCARE_LIST_SUCCESS'
export const DAYCARE_LIST_FAIL = 'DAYCARE_LIST_FAIL'

export const DAYCARE_DETAILS_REQUEST = 'DAYCARE_DETAILS_REQUEST'
export const DAYCARE_DETAILS_SUCCESS = 'DAYCARE_DETAILS_SUCCESS'
export const DAYCARE_DETAILS_FAIL = 'DAYCARE_DETAILS_FAIL'
