export const KID_LIST_REQUEST = 'KID_LIST_REQUEST'
export const KID_LIST_SUCCESS = 'KID_LIST_SUCCESS'
export const KID_LIST_FAIL = 'KID_LIST_FAIL'

export const KID_DETAILS_REQUEST = 'KID_DETAILS_REQUEST'
export const KID_DETAILS_SUCCESS = 'KID_DETAILS_SUCCESS'
export const KID_DETAILS_FAIL = 'KID_DETAILS_FAIL'
